# render.yaml — Configuration automatique du service
# https://render.com/docs/render-yaml

services:
  - type: web
    name: ask-jesus
    env: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        value: 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
      - key: UCEM_FILE
        value: /app/ucem_context.txt
